# Generated by Django 4.0.4 on 2022-04-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0002_musiclibrary_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='musiclibrary',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
